def switch_asl(argument):
    switcher = {
        'A': "D://6th SEM//6th_sem_projects//AIML//FInal project demo//Sign-Language-to-Text-master//textToimg//A.jpg",
        'B': "D://6th SEM//6th_sem_projects//AIML//FInal project demo//Sign-Language-to-Text-master//textToimg//A.jpg",
        'C': "D://6th SEM//6th_sem_projects//AIML//FInal project demo//Sign-Language-to-Text-master//textToimg//A.jpg",
        'D': "D://6th SEM//6th_sem_projects//AIML//FInal project demo//Sign-Language-to-Text-master//textToimg//D.jpg",
        'E': "D://6th SEM//6th_sem_projects//AIML//FInal project demo//Sign-Language-to-Text-master//textToimg//E.jpg",
        'F': "D://6th SEM//6th_sem_projects//AIML//FInal project demo//Sign-Language-to-Text-master//textToimg//F.jpg",
        'G': "D://6th SEM//6th_sem_projects//AIML//FInal project demo//Sign-Language-to-Text-master//textToimg//G.jpg",
        'H': "D://6th SEM//6th_sem_projects//AIML//FInal project demo//Sign-Language-to-Text-master//textToimg//H.jpg",
        'I': "D://6th SEM//6th_sem_projects//AIML//FInal project demo//Sign-Language-to-Text-master//textToimg//I.jpg",
        'J': "D://6th SEM//6th_sem_projects//AIML//FInal project demo//Sign-Language-to-Text-master//textToimg//J.jpg",
        'K': "D://6th SEM//6th_sem_projects//AIML//FInal project demo//Sign-Language-to-Text-master//textToimg//K.jpg",
        'L': "D://6th SEM//6th_sem_projects//AIML//FInal project demo//Sign-Language-to-Text-master//textToimg//L.jpg",
        'M': "D://6th SEM//6th_sem_projects//AIML//FInal project demo//Sign-Language-to-Text-master//textToimg//M.jpg",
        'N': "D://6th SEM//6th_sem_projects//AIML//FInal project demo//Sign-Language-to-Text-master//textToimg//N.jpg",
        'O': "D://6th SEM//6th_sem_projects//AIML//FInal project demo//Sign-Language-to-Text-master//textToimg//O.jpg",
        'P': "D://6th SEM//6th_sem_projects//AIML//FInal project demo//Sign-Language-to-Text-master//textToimg//P.jpg",
        'Q': "D://6th SEM//6th_sem_projects//AIML//FInal project demo//Sign-Language-to-Text-master//textToimg//Q.jpg",
        'R': "D://6th SEM//6th_sem_projects//AIML//FInal project demo//Sign-Language-to-Text-master//textToimg//R.jpg",
        'S': "D://6th SEM//6th_sem_projects//AIML//FInal project demo//Sign-Language-to-Text-master//textToimg//S.jpg",
        'T': "D://6th SEM//6th_sem_projects//AIML//FInal project demo//Sign-Language-to-Text-master//textToimg//T.jpg",
        'U': "D://6th SEM//6th_sem_projects//AIML//FInal project demo//Sign-Language-to-Text-master//textToimg//U.jpg",
        'V': "D://6th SEM//6th_sem_projects//AIML//FInal project demo//Sign-Language-to-Text-master//textToimg//V.jpg",
        'W': "D://6th SEM//6th_sem_projects//AIML//FInal project demo//Sign-Language-to-Text-master//textToimg//W.jpg",
        'X': "D://6th SEM//6th_sem_projects//AIML//FInal project demo//Sign-Language-to-Text-master//textToimg//X.jpg",
        'Y': "D://6th SEM//6th_sem_projects//AIML//FInal project demo//Sign-Language-to-Text-master//textToimg//Y.jpg",
        'Z': "D://6th SEM//6th_sem_projects//AIML//FInal project demo//Sign-Language-to-Text-master//textToimg//Z.jpg",
    }

    return switcher.get(argument, "nothing")
