def switch_isl(argument):
    switcher = {
        'A': "C://Users//sanja//Desktop//Sign-Language-to-Text-master//textToimgISL//A.jpg",
        'B': "C://Users//sanja//Desktop//Sign-Language-to-Text-master//textToimgISL//B.jpg",
        'C': "C://Users//sanja//Desktop//Sign-Language-to-Text-master//textToimgISL//C.jpg",
        'D': "C://Users//sanja//Desktop//Sign-Language-to-Text-master//textToimgISL//D.jpg",
        'E': "C://Users//sanja//Desktop//Sign-Language-to-Text-master//textToimgISL//E.jpg",
        'F': "C://Users//sanja//Desktop//Sign-Language-to-Text-master//textToimgISL//F.jpg",
        'G': "C://Users//sanja//Desktop//Sign-Language-to-Text-master//textToimgISL//G.jpg",
        'H': "C://Users//sanja//Desktop//Sign-Language-to-Text-master//textToimgISL//H.jpg",
        'I': "C://Users//sanja//Desktop//Sign-Language-to-Text-master//textToimgISL//I.jpg",
        'J': "C://Users//sanja//Desktop//Sign-Language-to-Text-master//textToimgISL//J.jpg",
        'K': "C://Users//sanja//Desktop//Sign-Language-to-Text-master//textToimgISL//K.jpg",
        'L': "C://Users//sanja//Desktop//Sign-Language-to-Text-master//textToimgISL//L.jpg",
        'M': "C://Users//sanja//Desktop//Sign-Language-to-Text-master//textToimgISL//M.jpg",
        'N': "C://Users//sanja//Desktop//Sign-Language-to-Text-master//textToimgISL//N.jpg",
        'O': "C://Users//sanja//Desktop//Sign-Language-to-Text-master//textToimgISL//O.jpg",
        'P': "C://Users//sanja//Desktop//Sign-Language-to-Text-master//textToimgISL//P.jpg",
        'Q': "C://Users//sanja//Desktop//Sign-Language-to-Text-master//textToimgISL//Q.jpg",
        'R': "C://Users//sanja//Desktop//Sign-Language-to-Text-master//textToimgISL//R.jpg",
        'S': "C://Users//sanja//Desktop//Sign-Language-to-Text-master//textToimgISL//S.jpg",
        'T': "C://Users//sanja//Desktop//Sign-Language-to-Text-master//textToimgISL//T.jpg",
        'U': "C://Users//sanja//Desktop//Sign-Language-to-Text-master//textToimgISL//U.jpg",
        'V': "C://Users//sanja//Desktop//Sign-Language-to-Text-master//textToimgISL//V.jpg",
        'W': "C://Users//sanja//Desktop//Sign-Language-to-Text-master//textToimgISL//W.jpg",
        'X': "C://Users//sanja//Desktop//Sign-Language-to-Text-master//textToimgISL//X.jpg",
        'Y': "C://Users//sanja//Desktop//Sign-Language-to-Text-master//textToimgISL//Y.jpg",
        'Z': "C://Users//sanja//Desktop//Sign-Language-to-Text-master//textToimgISL//Z.jpg",
    }

    return switcher.get(argument, "nothing")
